### ISSUE TITLE
Navbar not filling width on android

### ISSUE THREAD

**Issue by fredrikburmester** [callstackincubator/react-native-bottom-tabs#78]
![Screenshot_1730038435](https://github.com/user-attachments/assets/d44dd645-24d1-4450-8310-f54894cac2ae)

**Comment by fredrikburmester** [comment]
<img width="971" alt="Screenshot 2024-10-27 at 15 21 12" src="https://github.com/user-attachments/assets/a6fe2326-831c-4be4-a5b9-ee913ab94d2c">

**Comment by okwasniewski** [comment]
Tried to reproduce it in the repo example app and couldn't (bare workflow). Not sure if it's related to expo / expo router. Will investigate.

**Comment by okwasniewski** [comment]
Hey @fredrikburmester, 

I've tested this on Expo and also couldn't reproduce. Can you provide a minimal reproducible example? It might be an issue with yoga that it doesn't trigger measurements. 

![CleanShot 2024-10-29 at 11 26 01@2x](https://github.com/user-attachments/assets/3494ba6a-ba8c-4b60-ae06-ac28da4274d0)

**Comment by okwasniewski** [comment]
@fredrikburmester I've re-tested it in your app was really curious about what is happening there, looks like with fixes from #122 its working great. 

![CleanShot 2024-11-04 at 20 35 57@2x](https://github.com/user-attachments/assets/5fe3d745-54e6-4979-a378-b46d07fc825b)

**Comment by fredrikburmester** [comment]
Oh wow, thank you so much!
